name: radix-job-scheduler-server-build
on:
  push:
    branches: [main, release]
permissions:
  id-token: write
jobs:
  build-deploy-image-dev:
    name: Build-push to dev
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: radix-job-scheduler-server
    steps:
      - uses: actions/checkout@v1
      - name: 'Build docker image'
        run: |
          docker build -t radixdev.azurecr.io/$IMAGE_NAME:main-latest .
      - name: 'Login to dev'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: 'Push to dev'
        run: |
          az acr login --name radixdev
          docker push radixdev.azurecr.io/$IMAGE_NAME:main-latest
  build-deploy-image-prod:
    if: github.ref == 'refs/heads/release'
    name: Build-push to prod
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: radix-job-scheduler-server
    steps:
      - uses: actions/checkout@v1
      - name: 'Build docker image'
        run: |
          docker build -t radixprod.azurecr.io/$IMAGE_NAME:release-latest .
      - name: 'Login to prod'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
      - name: 'Push to prod'
        run: |
          az acr login --name radixprod
          docker push radixprod.azurecr.io/$IMAGE_NAME:release-latest
